### ISSUE TITLE
[bug] cannot install operator 

### ISSUE THREAD

**Issue by jiaoew1991** [milvus-io/milvusctl#9]
run command `./milvusctl operator install -v 0.5.0` then panic
![image](https://user-images.githubusercontent.com/2297455/182991161-6d82108d-1f1e-42d0-9e5a-c532c501ca84.png)

**Comment by Bennu-Li** [comment]
It is because the k8s cluster is not connected, please check the cluster environment.
I will fix the exception thrown when the cluster is not connected in the next release.
